### ISSUE TITLE
be-pretty does nothing at all?

### ISSUE THREAD

**Issue by isocra** [capaj/be-pretty#11]
Hi, 

I've tried `be-pretty` using first `npx be-pretty`, then installing using `npm i be-pretty -g`, then installing it locally.

Each time I try the following commands:
```
> be-pretty                                    
> be-pretty run                                
> be-pretty help
> be-pretty --help
> be-pretty usage 
```
Or when trying the local version
```
> node node_modules/be-pretty/dist/be-pretty.js usage
```
But I get no output at all, no error message nothing. 

I have `npm v6.9.0` and `node v12.4.0`. What am I doing wrong?

Thanks!

**Comment by capaj** [comment]
Hey @isocra, thanks for the report!
There was indeed a bug introduced in 0.9.4. I haven't noticed it, because I was still using the older version.

This was resolved in 1.0.0 so please give that one a shot next time you are bootstrapping prettier.
